### PR TITLE
PDMO-39: Enable retrieving and restoring voided observations 

### PR DESCRIPTION
**Pull request by Ewanjiru**
# JIRA TICKET NAME:
[Enable retrieving and restoring voided observations](https://issues.openmrs.org/browse/PDMO-39)

# SUMMARY:

Currently the voided observations can not be retrieved. In this PR we have added functionality to enable retrieving and undeleting of the voided observations.

### CODE REVIEW

**Comment by Farhanisto** [comment]
Looks good

**Comment by dkayiwa** [comment]
@Ewanjiru can you look into these merge conflicts?

**Comment by Ewanjiru** [comment]
@dkayiwa 
conflict has been resolved.

**Comment by dkayiwa** [comment]
@Ewanjiru can we get another review from andela?

**Comment by cnagadya** [comment]
Good work Eunice. Though from the screen shots, the buttons could be better aligned.

**Comment by dkayiwa** [comment]
@Ewanjiru what do you think of the button alignment comment from @cnagadya?

**Comment by Ewanjiru** [comment]
@cnagadya  thanks for the review. Please clarify on 'better aligned'. What do you feel is off with the current buttons so that I can know what to change.

**Comment by cnagadya** [comment]
Check [this](https://ux.stackexchange.com/questions/3340/while-designing-web-forms-should-the-buttons-be-left-aligned-or-right-aligned) out, especially the second answer from Herman. You could try aligning them with the input fields

**Review by malmike — COMMENTED** [review]
Looks good

**Comment by Ewanjiru** [comment]
@cnagadya I have implemented feedback as discussed earlier.

**Pull request merged**
