### PR TITLE
[New Feature] Demographics Component

### PR DESCRIPTION
**Pull request by CeciliaWanjiku**
JIRA TICKET NAME:

PDMO-6: [Component for managing patients demographics](https://issues.openmrs.org/browse/PDMO-6)

SUMMARY:
The component should consume and display patient demographics including information such as gender, birth date and deceased.
The component should allow one to edit and update this info

### CODE REVIEW

**Comment by dkayiwa** [comment]
Can you squash these commits into one as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by CeciliaWanjiku** [comment]
@dkayiwa Done.
Though the second commit has come from resolving merge conflicts

**Comment by dkayiwa** [comment]
I think you committed some of these changes accidentally. For instance, take a look at files with a path like "Users/ceciliawahome/Desktop/openmrs/" etc
Can you review the commit yourself and ensure that it has only the changes you intended to commit?

**Comment by CeciliaWanjiku** [comment]
@dkayiwa Done

**Comment by dkayiwa** [comment]
Did you take a look at the pull request tips i put above and followed them when committing and creating this pull request?

**Comment by CeciliaWanjiku** [comment]
@dkayiwa Apologies for this. I focused more on the commits and PR

**Pull request merged**
