### PR TITLE
PDMO-37 Revise PDM owa UI

### PR DESCRIPTION
**Pull request by jacksono**
## JIRA TICKET NAME:

[PDMO-37 Revise PDMO UI](https://issues.openmrs.org/browse/PDMO-37)

## SUMMARY:
Correct some inconsistencies noticed ie:
1. Uniform alignment for all the forms
2. Include inner padding on the pages. Usually, there's some padding from the outer border.
3. All text boxes and other elements should be implemented with the same length.

### CODE REVIEW

**Comment by Ewanjiru** [comment]
On the screenshots in Jira, I note the field labels are aligned right which looks rather inconsistent in my opinion due to the difference in number of chars per label.

**Comment by jacksono** [comment]
@Ewanjiru thanks for the review. As we agreed with the  team today, we shall remain with the right aligned labels since they leave less space between the label and the input box.

**Review by Farhanisto — COMMENTED** [review]
This looks good.

**Comment by jacksono** [comment]
Thanks @Farhanisto  and @Ewanjiru  for the reviews

**Comment by dkayiwa** [comment]
Can you look at the merge conflicts here?

**Comment by jacksono** [comment]
Okay.

**Comment by jacksono** [comment]
@dkayiwa Conflicts resolved.

**Pull request merged**
