### PR TITLE
[PDMO-75]-Enable filtering by Type, Visit and Date Range

### PR DESCRIPTION
**Pull request by Farhanisto**
## JIRA TICKET NAME:

[PDMO-75 Enable filtering by Type, Visit and Date Range](https://issues.openmrs.org/browse/PDMO-75)

## SUMMARY:
Encounters are shown in a table with columns for Type, Location Date and Visit.
In this task, enable filtering of encounters by Type, Visit and Date range

### CODE REVIEW

**Comment by Ewanjiru** [comment]
good job.

**Comment by jacksono** [comment]
Looks good

**Comment by dkayiwa** [comment]
Can you look into these merge conflicts?

**Comment by Farhanisto** [comment]
@dkayiwa I have sorted the merge conflict

**Pull request merged**
