### PR TITLE
PDMO-98: Fix Failing tests

### PR DESCRIPTION
**Pull request by aenkya**
## JIRA TICKET NAME:
[[PDMO-98] Fix Failing tests](https://issues.openmrs.org/browse/PDMO-98)
### SUMMARY:

Currently, running 
```
npm run test
```
runs and yields `4 failing tests`

The objective is to fix the failing tests

### CODE REVIEW

**Review by malmike — COMMENTED** [review]
Looks good

**Comment by segunolalive** [comment]
LGTM

**Comment by justmesam** [comment]
LGTM

**Comment by dkayiwa** [comment]
@Elbertbiggs360 can you include the ticket number in your commit message?

**Comment by aenkya** [comment]
@dkayiwa done

**Pull request merged**
