### PR TITLE
[PDMO-72]:Divide up the display of encounters and visits

### PR DESCRIPTION
**Pull request by jacksono**
## JIRA TICKET NAME:

[PDMO-72 Divide up the display of encounters and visits](https://issues.openmrs.org/browse/PDMO-72)

## SUMMARY:
Create two separate tables in the existing tabs to display visits and encounters in reverse chronological order instead of displaying them under one table

### CODE REVIEW

**Comment by Ewanjiru** [comment]
Looks good.

**Comment by Farhanisto** [comment]
Looks good.

**Comment by jacksono** [comment]
thanks @Ewanjiru  and @Farhanisto  for the review

**Review by chibujax — COMMENTED** [review]
Looks good

**Comment by jacksono** [comment]
Thanks @andela-cuchendu

**Pull request merged**
