### PR TITLE
[ Feature pdmo-32] Create tabs for visits and encounters in the collapsible

### PR DESCRIPTION
**Pull request by CeciliaWanjiku**
JIRA TICKET NAME:

PDMO-32: [Create tabs for visits and encounters in the collapsible](https://issues.openmrs.org/browse/PDMO-32)

SUMMARY:
Make it easy for one to navigate between encounters with visits and encounters without by using tabs instead of buttons

### CODE REVIEW

**Review by chibujax — COMMENTED** [review]
Can you change visitsTr to another meaningful name?
Other changes look good.

**Comment by Ewanjiru** [comment]
Add  single empty line after functions for good code format.

**Comment by CeciliaWanjiku** [comment]
@andela-cuchendu  @Ewanjiru Done

**Comment by chibujax** [comment]
We need to document our classes and functions. I understand it can be a lot of work to write the docs after building, but please can you add this?”

**Comment by CeciliaWanjiku** [comment]
@andela-cuchendu Done

**Pull request merged**
