### PR TITLE
[feature] Component for searching and listing patients

### PR DESCRIPTION
**Pull request by chibujax**
# JIRA TICKET NAME:
PDMO-8: [Component for searching and listing patients](https://issues.openmrs.org/browse/PDMO-8)

## SUMMARY:
Search for patients and list results

### CODE REVIEW

**Comment by dkayiwa** [comment]
@andela-cuchendu there are too many changes in this pull request. Are they all to do with this ticket?

**Comment by chibujax** [comment]
Yes @dkayiwa I am the first to start work so I basically configured and set up everything required. The many files came from the library folder

**Comment by dkayiwa** [comment]
In that case, create a separate pull request that deals with just setup issues.
Then create another pull request that deals with only the component required by the ticket.
Does this make sense?

**Comment by chibujax** [comment]
ok then, thank you.

**Pull request closed without merging**
